### ISSUE TITLE
Question about manual serialization

### ISSUE THREAD

**Issue by mabasic** [Zaid-Ajaj/Fable.SimpleJson#68]
In the readme under Manual serialization is this example:

```
let person = { Name = "John"; Age = 34 }

let serialized =
    [ "name", JString person.Name
      "age", JNumber (float person.Age) ]
    |> Map.ofList
    |> JObject
    |> SimpleJson.toString
```

I have used anonymous records with `Json.serialize` to avoid using the above code and it works.

```
let person = { Name = "John"; Age = 34 }

Json.serialize {| name = person.Name ; age = person.Age |}
```

What are the benefits/drawback to using your example and using anonymous records?

Should I send a PR to update the readme to use anonymous records?

**Comment by Zaid-Ajaj** [comment]
Hi @mabasic there is a big difference here because using a `Map -> `JObject` means that you can dynamically add or remove properties at runtime where as an anonymous record will have a static shape. You can add it to the README if you want, both ways are valid, though the first example is lower-level and most people will probably need the second one with anonymous records
